### ISSUE TITLE
controller containers don't restart after fresh install

### ISSUE THREAD

**Issue by joaocosta** [avinetworks/ansible-role-avicontroller#20]
When "fresh_install: true",  con_disk_path, con_metrics_disk_path and con_logs_disk_path are removed and recreated.  One or more of these is mounted as a bind volume inside the docker container.

If there is a pre-existing controller instance running, and I run the avicontroller role, then the bind volumes are lost as the original directories were deleted.

I imagine the controller needs restarting when fresh_install is true.

**Comment by ericsysmin** [comment]
added to a new patch 
`service: name=avicontroller enabled=yes state=restarted
  when: avicontroller_service.changed or load_docker_repo.changed or load_docker_hub.changed or fresh_install`

**Comment by ericsysmin** [comment]
Actually, I will add a stop betfore we get rid of those paths, when we do fresh install, might be better rofl
